### ISSUE TITLE
run 

### ISSUE THREAD

**Issue by chnasln** [sayan83/crowdless-people-counter#1]
Hi,
can you help me please ?
what is the   socketApi ?

socketApi = ""  # Add the socket api here

**Comment by sayan83** [comment]
Hello,

This project uses websockets to connect to a backend server and updates the count statistics(no of entry or no of exit) at the server every time there is a new count(entry or exit).

socketApi is the api endpoint for the server.

Hope this helps you.

**Comment by sayan83** [comment]
Closing this.
Reopen if still help is needed.
